### ISSUE TITLE
diagnostics app: show schema in dart syntax?

### ISSUE THREAD

**Issue by Dieterbe** [powersync-ja/powersync-js#306]
would be nice to show the schema in dart syntax so i can copypaste it straight into my codebase

**Comment by stevensJourney** [comment]
That would be nice. We currently do have schema generators in our [powersync-service](https://github.com/powersync-ja/powersync-service/blob/main/packages/sync-rules/src/DartSchemaGenerator.ts) repository. I believe we could use those in the Diagnostics tools.

**Comment by stevensJourney** [comment]
After reading this issue again I realise that this is linked to https://github.com/powersync-ja/powersync-js/issues/307. As mentioned there copying this into your codebase is not ideal. 

I would understand that a Dart developer might feel more comfortable seeing the Dart syntax for the schema in the Diagnostics app. That might make diagnostics easier since there is less mental translation required.

But that should not be used as a source of truth.

**Comment by Dieterbe** [comment]
ok given that the schema in the diagonstics app should not be relied upon to copy paste into the codebase, i think we can forget about my request for dart syntax
