### ISSUE TITLE
Question: Can a client track whether changes have been processed?

### ISSUE THREAD

**Issue by nthtrung09it** [powersync-ja/powersync-js#364]
I read the question "Can a client track whether changes have been processed?" in [the FAQ page].(https://docs.powersync.com/resources/faq)
Is there an easy way so that we only need to involve the client (react native app) to check if the changes have been processed?
I just thought that we can just observe the ps_crud table.

**Comment by rkistner** [comment]
If you just want to check whether there are changes in the upload queue, checking `select count() from ps_crud` will work. If you want to check whether there are pending changes for individual rows, the `ps_crud` table could perhaps work, but isn't indexed properly for that. I'd recommend using an approach like this instead:

1. Add a column for example `pending_changes` on the client only. Use a value of `true` / `1` to indicate there are pending changes not uploaded & processed by the server yet, and `null` if it has been processed.
2. Whenever you insert or modify a row on the client, set `pending_changes = true`.
3. In your `uploadData` function, ignore any updates to `pending_changes` (since the server does not know about the column).
4. When the update is processed by the server and synced back, it will be synced back without the `pending_changes` column, setting it back to null.

Does that give you what you need?

**Comment by nthtrung09it** [comment]
Just tested, and it worked. Tks @rkistner.
