### ISSUE TITLE
unsubscribe  watchWithCallback

### ISSUE THREAD

**Issue by YKX-A** [powersync-ja/powersync-js#378]
In this example, do I need to unsubscribe manually if I use watchWithCallback ?
```ts

  useEffect(() => {
    setLoading(true)
    
    const query = `
      SELECT id, name, created_by, DATE(created_at) as created_at
      FROM tb
      WHERE created_by = ?
    `

    powerSync.watch(
      query,
      [userId],
      {
        onResult: (result: QueryResult) => {
        setGroups(result.rows?._array as Group[] ?? [])
        },
        onError: (err) => {
        ...
        }
      }
    )
  }, [powerSync, userId])
```

**Comment by Chriztiaan** [comment]
Hey @YKX-A, you can look at how we cleanup the watch [here](https://github.com/powersync-ja/powersync-js/blob/main/packages/react/src/hooks/useQuery.ts#L120-L153) on the return of the `useEffect()`.
Is there a particular reason why you want to do this instead of using our `useQuery` hook which is available for React/React-native projects?

It's available [here](https://github.com/powersync-ja/powersync-js/blob/main/packages/react/README.md).
It handles the cleanup and effect managment for you.
