### ISSUE TITLE
Vite example shows this error `Could not POST streaming to /sync/stream` in `WebRemote.ts` and `404 Not Found http://localhost:3020/sync/stream`

### ISSUE THREAD

**Issue by guillempuche** [powersync-ja/powersync-js#93]
When running `example-vite` `pnpm dev` with `vite.config.ts`:
```ts
server: {
   port: 3020,
},
```

The web seems working. But my browser shows this error:

<img width="469" alt="imatge" src="https://github.com/powersync-ja/powersync-js/assets/3519924/f7b325bf-f500-4826-a649-5fe622a793f9">

```sh
Could not POST streaming to /sync/stream - 404 - Not Found: [WebRemote.ts:58:14](http://localhost:3020/@fs/Users/guillem/programacio/codi/cites/databases/powersync-js/packages/powersync-sdk-web/src/db/sync/WebRemote.ts)
```

And also `XHR POST http://localhost:3020/sync/stream [HTTP/1.1 404 Not Found 1ms]`

Do you know why?

**Comment by guillempuche** [comment]
I write the question here to be searchable in Google for others.

**Comment by stevensJourney** [comment]
Hi @guillempuche this is currently expected behaviour. 

The log above the error mentions that there aren't any actual backend credentials configured. This will cause any network requests to the PowerSync instance to fail. 

The connecting step is only included in the Vite example to verify that all web worker config has been bundled correctly.

**Comment by guillempuche** [comment]
Great @stevensJourney, I imagined this. To stop confusion, I'd add this hint to README, like linking it to this issue.

I'm working on integrating auth with Stytch https://stytch.com/ (support React and React Native). Let's see if I finish it and open source the example.
